"""Core ContractShield components."""

from .contract import (
    ContractConfig,
    LimitsConfig,
    PolicyDefaults,
    PolicyLoader,
    PolicyMode,
    PolicyRoute,
    PolicyRule,
    PolicySet,
    RouteMatch,
    RuleAction,
    RuleType,
    UnmatchedAction,
    VulnerabilityChecksConfig,
    WebhookConfig,
)
from .errors import (
    CELEvaluationError,
    ConfigurationError,
    ContractShieldError,
    PolicyError,
    ValidationError,
    VulnerabilityDetectedError,
)
from .result import (
    Action,
    ClientInfo,
    Decision,
    Identity,
    RedactionDirective,
    RequestBody,
    RequestContext,
    RiskLevel,
    RiskScore,
    RuleHit,
    RuntimeInfo,
    Severity,
    ValidationResult,
    WebhookInfo,
)
from .validator import ContractValidator, DefaultSchemaLoader, SchemaLoader, resolve_schema_ref

__all__ = [
    # Result types
    "Action",
    "Severity",
    "RiskLevel",
    "RuleHit",
    "RiskScore",
    "Decision",
    "ValidationResult",
    "RedactionDirective",
    "RequestBody",
    "Identity",
    "ClientInfo",
    "RuntimeInfo",
    "WebhookInfo",
    "RequestContext",
    # Contract/Policy types
    "PolicyMode",
    "UnmatchedAction",
    "RuleType",
    "RuleAction",
    "LimitsConfig",
    "VulnerabilityChecksConfig",
    "ContractConfig",
    "WebhookConfig",
    "PolicyRule",
    "RouteMatch",
    "PolicyRoute",
    "PolicyDefaults",
    "PolicySet",
    "PolicyLoader",
    # Validator
    "ContractValidator",
    "SchemaLoader",
    "DefaultSchemaLoader",
    "resolve_schema_ref",
    # Errors
    "ContractShieldError",
    "ValidationError",
    "ConfigurationError",
    "PolicyError",
    "CELEvaluationError",
    "VulnerabilityDetectedError",
]
